src/components/button/Button.stories.tsx, src/styles/common/_colors.scss, src/styles/common/_fonts.scss, src/styles/common/_layout.scss, src/styles/common/_mixins.scss, src/styles/components/Button.scss
=> [OBSDEF-14005] Wrapper for button

src/components/input/Input.stories.tsx, src/styles/common/_layout.scss, src/styles/components/Button.scss, src/styles/components/Input.scss
Updated the direct use of input element to clr-input class.
Removed isBoxed property
Updated few css.
=> Updating input wrapper CSS

src/components/textarea/TextArea.stories.tsx, src/styles/common/_borders.scss, src/styles/common/_colors.scss, src/styles/common/_fonts.scss, src/styles/common/_layout.scss, src/styles/common/_mixins.scss, src/styles/components/TextArea.scss, src/styles/index.scss
=> [OBSDEF-13998] TextArea wrapper changes

src/components/button/Button.stories.tsx, src/styles/common/_fonts.scss, src/styles/components/Button.scss
Fixing button font size. making it important as it is getting overridden in UI.
=> Fixing font size.

src/styles/common/_fonts.scss, src/styles/common/_layout.scss, src/styles/common/_mixins.scss, src/styles/components/DataGrid.scss
Test Url: http://10.249.253.4:3001
token: 
eyJhbGciOiJSUzI1NiIsImtpZCI6Ik85MENqVU9aMkQxbTRnR2xZZGItREF6Y01oR0xFMjFCMHoweUs1SjBnR2MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMxMDA4Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im9iamVjdHNjYWxlLW9wZXJhdG9yLXRva2VuLWNoY2w1Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Im9iamVjdHNjYWxlLW9wZXJhdG9yIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTU0MmYxYjctMTQ0Yy00NjQ2LThiZWMtOTVjNjU1ZWQwNTA0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN2Yy1vYmplY3RzY2FsZS1kb21haW4tYzEwMDg6b2JqZWN0c2NhbGUtb3BlcmF0b3IifQ.G3UbJsNw6ftqwqaBqPxF2wPAxY5CN5eNsLrBWqZyr3gT0ENp5Ab9HKM5Fya7Y3d8dL6SkdXWB0fpNhORqqsz_-NJUPq …
=> OBSDEF-13985-DatagridWrapper

src/components/wizard/Wizard.stories.tsx, src/components/wizard/WizardUtility.tsx, src/styles/common/_colors.scss, src/styles/common/_fonts.scss, src/styles/common/_layout.scss, src/styles/components/Wizard.scss, src/styles/index.scss
Testing link : http://10.249.253.4:3000
key: eyJhbGciOiJSUzI1NiIsImtpZCI6IlloNmpYd3RRcUMwQTlVUmRac005ZlFLS0k3VlI5S2Jvc3BrRUdScVRjQ0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi1wa2h4MiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZiYmNmNDk3LTgzOWYtNDZjMC1hMzQ5LTg3ZTkzY2UwN2Y5NCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMDpvYmplY3RzY2FsZS1vcGVyYXRvciJ9.MzDyDe3E8WjsW8dyz9Y2bNEKA3VgS7DPi4ScjUgr0FMHGuLekUMHS_4PGDJV52nuF1YOzD-lUrlQ7n-BXsY532Gd1WVK9cg …
=> Obsdef 13989 wizard wrapper

src/components/table/Table.stories.tsx, src/styles/common/_borders.scss, src/styles/components/Table.scss, src/styles/index.scss
Test link: http://10.249.253.4:3000
token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlloNmpYd3RRcUMwQTlVUmRac005ZlFLS0k3VlI5S2Jvc3BrRUdScVRjQ0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi1wa2h4MiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZiYmNmNDk3LTgzOWYtNDZjMC1hMzQ5LTg3ZTkzY2UwN2Y5NCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMDpvYmplY3RzY2FsZS1vcGVyYXRvciJ9.MzDyDe3E8WjsW8dyz9Y2bNEKA3VgS7DPi4ScjUgr0FMHGuLekUMHS_4PGDJV52nuF1YOzD-lUrlQ7n-BXsY532Gd1WVK9cg1y …
=> Table Wrapper changes

src/components/accordion/Accordian.stories.tsx, src/styles/components/Accordion.scss, src/styles/index.scss
Wrapper for accordion
Testing link: http://10.249.253.4:3000/
`eyJhbGciOiJSUzI1NiIsImtpZCI6IlloNmpYd3RRcUMwQTlVUmRac005ZlFLS0k3VlI5S2Jvc3BrRUdScVRjQ0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtdWkyLWRvbWFpbi1jMjAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoib2JqZWN0c2NhbGUtb3BlcmF0b3ItdG9rZW4tZGdjZ20iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoib2JqZWN0c2NhbGUtb3BlcmF0b3IiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkNzRlMmExNy0wNGEzLTQ2NTAtODM5ZC03NTY1MDIzZGY5ODMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6c3ZjLW9iamVjdHNjYWxlLXVpMi1kb21haW4tYzIwOm9iamVjdHNjYWxlLW9wZXJhdG9yIn0.m1sB5UEQIK5q6uhbSbqsmr0pbGwYlGwOSabO8SPt3GuvHGfK6hTNEtSqU5f3ETjFS0 …
=> [OBSDEF-13982] Wrapper for accordion

yarn.lock
Update yarnlock to resolve build issue
=> Update yarnlock to resolve build issue

package.json
=> Update version for build

src/components/modals/Modals.stories.tsx, src/styles/common/_fonts.scss, src/styles/components/Modals.scss, src/styles/index.scss
Css wrapper for Modals
Testing link: http://10.249.253.4:3000/
`eyJhbGciOiJSUzI1NiIsImtpZCI6IlloNmpYd3RRcUMwQTlVUmRac005ZlFLS0k3VlI5S2Jvc3BrRUdScVRjQ0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi1wa2h4MiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZiYmNmNDk3LTgzOWYtNDZjMC1hMzQ5LTg3ZTkzY2UwN2Y5NCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMDpvYmplY3RzY2FsZS1vcGVyYXRvciJ9.MzDyDe3E8WjsW8dyz9Y2bNEKA3VgS7DPi4ScjUgr0FMHGuLekUMHS_4PGDJV52nuF1YOzD-lUrlQ …
=> [OBSDEF-13988] Css wrapper for Modals

src/components/spinner/Spinner.stories.tsx, src/styles/common/_fonts.scss, src/styles/common/_layout.scss, src/styles/common/_mixins.scss, src/styles/components/Spinner.scss, src/styles/index.scss
Css wrapper for spinner
Testing link: http://10.249.253.4:3000/
`eyJhbGciOiJSUzI1NiIsImtpZCI6IlloNmpYd3RRcUMwQTlVUmRac005ZlFLS0k3VlI5S2Jvc3BrRUdScVRjQ0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi1wa2h4MiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZiYmNmNDk3LTgzOWYtNDZjMC1hMzQ5LTg3ZTkzY2UwN2Y5NCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMDpvYmplY3RzY2FsZS1vcGVyYXRvciJ9.MzDyDe3E8WjsW8dyz9Y2bNEKA3VgS7DPi4ScjUgr0FMHGuLekUMHS_4PGDJV52nuF1YOzD-lUrl …
=> [OBSDEF-13991] Css wrapper for spinner

src/components/layout/nav/Header.stories.tsx, src/styles/components/Navigation.scss, src/styles/index.scss
test link: http://10.249.253.4:3001
token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlloNmpYd3RRcUMwQTlVUmRac005ZlFLS0k3VlI5S2Jvc3BrRUdScVRjQ0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi1wa2h4MiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZiYmNmNDk3LTgzOWYtNDZjMC1hMzQ5LTg3ZTkzY2UwN2Y5NCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMDpvYmplY3RzY2FsZS1vcGVyYXRvciJ9.MzDyDe3E8WjsW8dyz9Y2bNEKA3VgS7DPi4ScjUgr0FMHGuLekUMHS_4PGDJV52nuF1YOzD-lUrlQ7n-BXsY532Gd1WVK9cg1y …
=> Obsdef 13987 top navigation wrapper

src/components/tooltip/ToolTip.stories.tsx, src/styles/common/_colors.scss, src/styles/common/_fonts.scss, src/styles/common/_mixins.scss, src/styles/components/ToolTip.scss, src/styles/index.scss
Testing link
https://10.249.253.4:3003/
Tooltip DDS style on Standalone
Tooltip verification on vsphere
=> Feature obsdef 13999 tooltip wrapper

src/components/password/Password.stories.tsx, src/styles/components/Password.scss, src/styles/index.scss
Test URL: http://10.249.253.4:3001
Token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlNBOXhpNnN4UlpYMEdhZEdiNUllZzBWYmR5U3k1VVdJRFI1TXBoTFFfd00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi10NzlzdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQ0ODFiY2I2LTQ3NjQtNGI2MC05ZTM2LTIxYjMwMmY1N2JlMCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMDpvYmplY3RzY2FsZS1vcGVyYXRvciJ9.pL3Lgv_1aC9GrXWR1MzDVfTZCoGU2Y8U2ZgXvUAX-H7ka30whDN7qPCN12-YEexmSS9WLHsidArbPtYlKM0vl4deF8rbD58TRX …
=> Obsdef 15340 password wrapper

src/components/toggle/Toggle.stories.tsx, src/styles/components/Toggle.scss
This PR contains dell design wrapper changes for toggle.
=> [OBSDEF-15341] Toggle CSS changes

src/components/datepicker/DatePicker.stories.tsx, src/styles/common/_mixins.scss, src/styles/components/DatePicker.scss, src/styles/components/Password.scss, src/styles/index.scss
Test link: http://10.249.253.4:3001/
Token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlNBOXhpNnN4UlpYMEdhZEdiNUllZzBWYmR5U3k1VVdJRFI1TXBoTFFfd00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi10NzlzdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQ0ODFiY2I2LTQ3NjQtNGI2MC05ZTM2LTIxYjMwMmY1N2JlMCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMDpvYmplY3RzY2FsZS1vcGVyYXRvciJ9.pL3Lgv_1aC9GrXWR1MzDVfTZCoGU2Y8U2ZgXvUAX-H7ka30whDN7qPCN12-YEexmSS9WLHsidArbPtYlKM0vl4deF8rbD58T …
=> DatePicker Wrapper

package.json, src/components/dataGrid/DataGrid.stories.tsx, src/components/dataGrid/DataGridStoriesData.tsx, src/styles/common/_fonts.scss, src/styles/common/_layout.scss, src/styles/common/_mixins.scss, src/styles/components/DataGrid.scss
[OBSDEF-13990](https://jira.cec.lab.emc.com/browse/OBSDEF-13990)
Datagrid wrapper
Following are the changes:
- Corrected header and row height as per DDS
- Styles for buttons inside datagrid
- Style correction for detail pane
- Added styles for compact table
- Adjusted footer size
- Added relevant stories 
- Misc. styles fix
Testing link: http://10.249.253.4:3007/
Token: 
> eyJhbGciOiJSUzI1NiIsImtpZCI6IlNBOXhpNnN4UlpYMEdhZEdiNUllZzBWYmR5U3k1VVdJRFI1TXBoTFFfd00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi03eno0NSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1v …
=> [OBSDEF-13990] Datagrid wrapper

package.json, src/components/modals/Modals.stories.tsx, src/components/progressBar/ProgressBar.stories.tsx, src/styles/common/_colors.scss, src/styles/common/_layout.scss, src/styles/common/_mixins.scss, src/styles/components/Modals.scss, src/styles/components/ProgressBar.scss, src/styles/index.scss, yarn.lock
Summary of changes:
**Progress bars:**
- Changed colors of progress bar as per DDS
- Positioned label correctly 
- Styles for static, looped progress bar
- Added progress bar stories
**Modals:**
-  ~~Changed modals size as per DDS~~ (reverted this changes as it was braking modals in standalone UI)
- Added styles for title icons
- Updated modals stories as per type
~~[Note: PR validation will run successfully once [#240](https://github.com/EMCECS/clarity-react/pull/240) is merged]~~ (Passed)
Progress bar:
Modals;
=> [OBSDEF-15209][OBSDEF-13968] wrapper for progress bar and modal related changes

package.json, src/styles/components/Button.scss
[OBSDEF-19545](https://jira.cec.lab.emc.com/browse/OBSDEF-19544)
Convert button labels to title case
As per[ DDS](https://web.ddsproduct.com/31b3fd8b1/p/991830-buttons/b/479ce2),  title case for Buttons should be used. As of now casing is inconsistent for buttons.
en.json has inconsistent labels for buttons, for few buttons uppercase is used.
CSS property `text-transform` only capitalizes first letter of the word. So if word is already in uppercase it doesn't lowercase rest of the letters.
Hence, lowercasing the words first then capitalizing words.
(Attaching few screenshots only, please verify on possible button workflows)
http://10.249.253.4:3007/
```
eyJhbGciOiJSUzI1NiIsImtpZCI6Im9RNE1BLVlFNU5GYi1qZDdrTld1OG9yVmpmZXhHcW9USkJEWWZNM1MxV1UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiw …
```
=> [OBSDEF-19545] Convert button labels to title case

package.json, src/components/button/buttonGroup/ButtonGroup.stories.tsx, src/styles/common/_mixins.scss, src/styles/components/Badge.scss, src/styles/components/Button.scss, src/styles/components/Modals.scss, yarn.lock
Raised this PR on behalf of Bhawani as he is yet to get access.
[OBSDEF-19757](https://jira.cec.lab.emc.com/browse/OBSDEF-19757)
Spacing between buttons should be consistent
[OBSDEF-19539](https://jira.cec.lab.emc.com/browse/OBSDEF-19539)
The color of the button group should be as per DDS 
[OBSDEF-19811](https://jira.cec.lab.emc.com/browse/OBSDEF-19539)
The color of the blue badge should be as per DDS
http://10.249.253.4:3001/
```
eyJhbGciOiJSUzI1NiIsImtpZCI6Im9RNE1BLVlFNU5GYi1qZDdrTld1OG9yVmpmZXhHcW9USkJEWWZNM1MxV1UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi1qYjQycSIsImt1YmVybmV0ZXMuaW8vc2VydmljZW …
```
=> [OBSDEF-19757] Spacing between buttons should be consistent

package.json, src/styles/common/_layout.scss, src/styles/components/Alert.scss, src/styles/components/Button.scss
[OBSDEF-19679](https://jira.cec.lab.emc.com/browse/OBSDEF-19679)
- Some alert styles of DDRC were conflicting with clarity styles and hence little misalignment were seen.
- Earlier, all button text was capitalized from CSS, some side effects were observed due to that change hence reverting those changes as well
http://10.249.253.4:3007/
```
eyJhbGciOiJSUzI1NiIsImtpZCI6Im9RNE1BLVlFNU5GYi1qZDdrTld1OG9yVmpmZXhHcW9USkJEWWZNM1MxV1UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi1qYjQycSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2 …
```
=> [OBSDEF-19679] Styles fix for alerts

package.json, src/styles/common/_mixins.scss, src/styles/components/DataList.scss, src/styles/components/Select.scss
This PR changes with to max-width for these components:
1- input
2- select
3- datalist
Storybook gif:
=> [OBSDEF-19781] changed width to max-width

package.json, src/styles/components/Button.scss
Changes :
Removed focus border on button as it is creating issues at lot of places
App ss:
Storybook: http://10.249.253.4:6006
test: http://10.249.253.4:3003
use andre creds
=> [OBSDEF-19541] removed button focus

package.json, src/components/breadcrumb/Breadcrumb.tsx
This PR adds dataqa prop on both Breadcrumbs top level and items level
- No functionality changes or UI changes occurs from this PR
=> [OBSDFF-21236] Data QA on breadcrumbs

package.json, src/styles/components/DataGrid.scss
- Fix position of show hide dialog box
- Fix content and button position
http://10.249.253.4:6006/
=> [OBSDEF-23067] Fix datagrid show hide dialog position

src/components/breadcrumb/Breadcrumb.stories.tsx, src/components/breadcrumb/Breadcrumb.tsx, src/styles/components/Breadcrumb.scss
Implementation of Collapsible breadcrumbs functionality
- Check if the breadcrumbs should be collapsible or not
- Default: False
- If set to True, breadcrumbs trail will be truncated based on the maxItems prop
- Max breadcrumb items count, if breadcrumb count passes this threshold, breadcrumb body truncates into collapsed form 
- Default: 3
- _isCollapsible_ should be true for breadcrumbs collapse functionality to activate
http://10.249.253.4:6006/?path=/story/breadcrumb--default-breadcrumbs
=> [OBSDEF-24807] make breadcrumbs design as per DDS

package.json
This PR update the version, having collapsible breadcrumbs functionality.
=> [OBSDEF-25001] Bump version to 0.2.8

package.json, src/components/dataGrid/DataGridStoriesData.tsx, yarn.lock
[OBSDEF-44980](https://jira.cec.lab.emc.com/browse/OBSDEF-44980)
- Added code to show pagination footer with page sizes dropdown only if the total number of records are greater than 10
- Updated story data
- Updated version for packages
NA
Storybook:
Storybook : 
http://10.227.234.153:6006/ 
_List all the scenarios verified for the changes or link to the manual test documentation for new features_
_Add team member's name who will test your PR_
@netraja-chavan
=> [OBSDEF-44980] Show pagination footer with page sizes dropdown only if number of records are greater than 10
